### ISSUE TITLE
Declaration types are missing when re-export default multiple times

### ISSUE THREAD

**Issue by sedx** [wessberg/rollup-plugin-ts#109]
**Hi! First of all thanks for plugin that can bundle `d.ts` too! It's killer feature, realy!**

But I faced some issue, traditionally details below
_____

- Version: 1.3.2
- Rollup Version: 2.23.1
- Operating System and version (if applicable): macOS
- Node Version (if applicable): v12.13.1
- Does it work with `tsc` (if applicable): N/A

### Reproduction

I have package that contains some sub modules (each submodule is separate entry point). Entry point has named exports `View` and `Model` ([like this](https://github.com/sedx/rollup-ts-bug/blob/master/lib/A/index.ts))

I placed Views and Models to sub folders and re-export `default` up-to submodule entry point.

When I build package I get broken type definition. `View` exported with type `typeof default`, but [default](https://github.com/sedx/rollup-ts-bug/blob/master/build/A.d.ts#L6) is not defined 😔

Looks like reason is chain of `export { default } from './someSourceFile'`.

When I used named export all is fine. ([here is result for named exports](https://github.com/sedx/rollup-ts-bug/blob/master/build/B.d.ts#L8))

Repo with bug reproduction https://github.com/sedx/rollup-ts-bug
I added result of build to repo.

### Expected Behavior

```ts
declare const _default: {
    foo: string;
    baz: number;
};
declare const Model: typeof _default;
declare const View: typeof MainView(): JSX.Element;
export { Model, View };
//# sourceMappingURL=A.d.ts.map
```

### Actual Behavior
```ts
declare const _default: {
    foo: string;
    baz: number;
};
declare const Model: typeof _default;
// ⚠️ default here is not defined
declare const View: typeof default;
export { Model, View };
//# sourceMappingURL=A.d.ts.map
```

**Comment by wessberg** [comment]
Hey there.
It took me a few years apparently, but this bug has been fixed now and will be part of v2.0.6 when it releases soon.

**Comment by diego-toro** [comment]
hi @wessberg! Is it related to a bug I saw recently https://github.com/wessberg/rollup-plugin-ts/issues/176? By using re-exports, the resulting `d.ts` file doesn't resolve the inner types correctly. 
Is there a way for me to install the v2.0.6? I tried `npm i rollup-plugin-ts@next` but didn't resolve a version

**Comment by wessberg** [comment]
It is, yes. Your issue is covered by the fix too. It will be released shortly

**Comment by diego-toro** [comment]
That's Awesome! Thanks @wessberg

**Comment by wessberg** [comment]
[v2.0.6 has now been released](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v2.0.6)
